"""Mongo collection names. Backend owns persistence; do not invent parallel stores."""

PROJECTS = "projects"
PROJECT_SNAPSHOTS = "project_snapshots"
PREDICTIONS = "predictions"
EVENTS = "project_events"
ALERTS = "alerts"
INVESTIGATIONS = "investigations"
EVIDENCE = "evidence"
HYPOTHESES = "hypotheses"
RECOMMENDATIONS = "recommendations"
INTERVENTIONS = "interventions"
INTERVENTION_OUTCOMES = "intervention_outcomes"
PEER_ANALYSES = "peer_analyses"
DATA_QUALITY = "data_quality"
AUDIT_LOGS = "audit_logs"
NOTIFICATION_DELIVERIES = "notification_deliveries"
MODEL_METADATA = "model_metadata"
MONITORING_CYCLES = "monitoring_cycles"
USERS = "users"
OUTBOX = "outbox_events"
